server:
  port: 8080

app:
  jwt:
    secret: 7fG3kL9!xYpQ2rV8wT#sZd6mB0nC1vA5
    expirationMs: 3600000

spring:
  main:
    allow-circular-references: true
  application:
    name: SpringSecurityJWT
  datasource:
    url: jdbc:postgresql://localhost:5432/cp5db
    username: postgres
    password: admin1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  devtools:
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

logging:
  level:
    root: INFO
    br: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
